//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class konobar
    {
        public string jmbgradnika { get; set; }
        public Nullable<int> restoran_idrest { get; set; }
        public Nullable<int> godine_iskustva { get; set; }
    
        public virtual radnik radnik { get; set; }
        public virtual restoran restoran { get; set; }
    }
}
