//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGUI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class E31032014ProjekatEntities : DbContext
    {
        public E31032014ProjekatEntities()
            : base("name=E31032014ProjekatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<drzi> drzi { get; set; }
        public virtual DbSet<gost> gost { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<konobar> konobar { get; set; }
        public virtual DbSet<menadzer> menadzer { get; set; }
        public virtual DbSet<odseda> odseda { get; set; }
        public virtual DbSet<radnik> radnik { get; set; }
        public virtual DbSet<recepcionar> recepcionar { get; set; }
        public virtual DbSet<restoran> restoran { get; set; }
        public virtual DbSet<soba> soba { get; set; }
        public virtual DbSet<spremacica> spremacica { get; set; }
        public virtual DbSet<vlasnik> vlasnik { get; set; }
        public virtual DbSet<Audit> Audit { get; set; }
    
        public virtual int Procedura(string mbr)
        {
            var mbrParameter = mbr != null ?
                new ObjectParameter("Mbr", mbr) :
                new ObjectParameter("Mbr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Procedura", mbrParameter);
        }
    }
}
