//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class odseda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public odseda()
        {
            this.recepcionar = new HashSet<recepcionar>();
        }
    
        public int gost_jmbg { get; set; }
        public int soba_broj { get; set; }
        public int soba_hotel_idhotel { get; set; }
    
        public virtual gost gost { get; set; }
        public virtual soba soba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recepcionar> recepcionar { get; set; }
    }
}
