//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelGUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class radnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public radnik()
        {
            this.hotel = new HashSet<hotel>();
        }
    
        public string jmbgradnika { get; set; }
        public string ime_radnika { get; set; }
        public string prezime_radnika { get; set; }
    
        public virtual konobar konobar { get; set; }
        public virtual menadzer menadzer { get; set; }
        public virtual recepcionar recepcionar { get; set; }
        public virtual spremacica spremacica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel> hotel { get; set; }
    }
}
